/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import { JSX } from '@stencil/core';


export namespace Components {
  interface PjsWhiskers {
    'colour'?: "positive" | "negative";
  }
}

declare namespace LocalJSX {
  interface PjsWhiskers extends JSXBase.HTMLAttributes {
    'colour'?: "positive" | "negative";
  }

  interface ElementInterfaces {
    'PjsWhiskers': Components.PjsWhiskers;
  }

  interface IntrinsicElements {
    'PjsWhiskers': LocalJSX.PjsWhiskers;
  }
}
export { LocalJSX as JSX };

declare module "@stencil/core" {
  export namespace JSX {
    interface ElementInterfaces extends LocalJSX.ElementInterfaces {}
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}

declare global {


  interface HTMLPjsWhiskersElement extends Components.PjsWhiskers, HTMLStencilElement {}
  var HTMLPjsWhiskersElement: {
    prototype: HTMLPjsWhiskersElement;
    new (): HTMLPjsWhiskersElement;
  };
  interface HTMLElementTagNameMap {
    'pjs-whiskers': HTMLPjsWhiskersElement
  }

  interface ElementTagNameMap {
    'pjs-whiskers': HTMLPjsWhiskersElement;
  }
}

